### PR TITLE
Implementar persistencia

### PR DESCRIPTION
**Pull request by aangell98**
Implementacion de base de datos apache derby en el sistema

### CODE REVIEW

**Comment by aangell98** [comment]
He reportado el bug #3 que deberiamos solucionar antes de realizar la implementacion

**Comment by aangell98** [comment]
Tras solucionar el bug el codigo esta listo para su implementacion.

**Comment by Jennigg2** [comment]
Buenas Angel, presento fallos al ejecutar el código. Puesto que a ti te funciona, no será necesario generar un nuevo bug al ser un fallo personal, cuando este arreglado os aviso.
Información del error: PS C:\Users\jenni\OneDrive\Documents\Documents\3º CARRERA (1º Cuatri)\Ingneieria del software II\PROYECTO-ISO2> mvn spring-boot:run
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< es.uclm:library >---------------------------
[INFO] Building library 0.0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] >>> spring-boot:3.3.4:run (default-cli) > test-compile @ library >>>
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ library ---
[INFO] Copying 1 resource from src\main\resources to target\classes
[INFO] Copying 2 resources from src\main\resources to target\classes
[INFO]
[INFO] --- compiler:3.13.0:compile (default-compile) @ library ---
[INFO] Recompiling the module because of changed source code.
[INFO] Compiling 5 source files with javac [debug parameters release 17] to target\classes
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ library ---
[INFO] skip non existing resourceDirectory C:\Users\jenni\OneDrive\Documents\Documents\3º CARRERA (1º Cuatri)\Ingneieria del software II\PROYECTO-ISO2\src\test\resources
[INFO]
[INFO] --- compiler:3.13.0:testCompile (default-testCompile) @ library ---
[INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 1 source file with javac [debug parameters release 17] to target\test-classes
[INFO] 
[INFO] <<< spring-boot:3.3.4:run (default-cli) < test-compile @ library <<<
[INFO]
[INFO]
[INFO] --- spring-boot:3.3.4:run (default-cli) @ library ---
[INFO] Attaching agents: []
Error: Could not find or load main class es.uclm.library.LibraryApplication
Caused by: java.lang.ClassNotFoundException: es.uclm.library.LibraryApplication
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.402 s
[INFO] Finished at: 2024-10-04T13:09:25+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.3.4:run (default-cli) on project library: Process terminated with exit code: 1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Review by fferr184 — APPROVED** [review]
Tras revisar el código y solucionar los errores, por mi perfecto hacer el merge

**Review by Jennigg2 — COMMENTED** [review]
Todo solucionado y revisado podemos proceder para hacer el merge.

**Review by Jennigg2 — APPROVED** [review]

**Review by alvaaromora26 — COMMENTED** [review]
Esta correcto

**Review by alvaaromora26 — APPROVED** [review]

**Comment by aangell98** [comment]
Se realizo el merge de la rama de persistencia a develop con exito

**Pull request merged**
